language: javascript
script:
 - nvm install 
 - npm install
 - npm run-script build
 - phantomjs testrunner.js LOCALSTORAGE
 - phantomjs testrunner.js FLUSHALL
 - phantomjs testrunner.js KEYS
 - phantomjs testrunner.js LISTS
 - phantomjs testrunner.js SETS
